name: PostgreSQL Service Container

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gomtimehta1/postgres_service:latest

    - name: Deploy and Initialize PostgreSQL
      run: |
          docker pull gomtimehta1/postgres_service:latest
          docker run -d -p 5432:5432 gomtimehta1/postgres_service:latest       